export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Admin side bus facility
export const BUS_REQUEST = 'BUS_REQUEST';
export const BUS_FAILURE = 'BUS_FAILURE';
export const BUS_SUCCESS = 'BUS_SUCCESS';

//Ticket booking facility
export const ADDTICKET_REQUEST = 'ADDTICKET_REQUEST';
export const ADDTICKET_FAILURE = 'ADDTICKET_FAILURE';
export const ADDTICKET_SUCCESS = 'ADDTICKET_SUCCESS';

//Wallet
export const WALLET_REQUEST = 'WALLET_REQUEST';
export const WALLET_FAILURE = 'WALLET_FAILURE';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';

//UpdateSchedule
export const SCHEDULE_REQUEST = 'SCHEDULE_REQUEST';
export const SCHEDULE_FAILURE = 'SCHEDULE_FAILURE';
export const SCHEDULE_SUCCESS = 'SCHEDULE_SUCCESS';

//Store
export const STORE_REQUEST = 'STORE_REQUEST';
export const STORE_FAILURE = 'STORE_FAILURE';
export const STORE_SUCCESS = 'STORE_SUCCESS';

//OUTPASS
export const OUTPASS_REQUEST = 'OUTPASS_REQUEST';
export const OUTPASS_FAILURE = 'OUTPASS_FAILURE';
export const OUTPASS_SUCCESS = 'OUTPASS_SUCCESS';