export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Admin side add bus facility
export const ADDBUS_REQUEST = 'ADDBUS_REQUEST';
export const ADDBUS_FAILURE = 'ADDBUS_FAILURE';
export const ADDBUS_SUCCESS = 'ADDBUS_SUCCESS';

//Admin side remove bus facility
export const REMOVEBUS_REQUEST = 'REMOVEBUS_REQUEST';
export const REMOVEBUS_FAILURE = 'REMOVEBUS_FAILURE';
export const REMOVEBUS_SUCCESS = 'REMOVEBUS_SUCCESS';

//Ticket booking facility
export const BOOKTICKET_REQUEST = 'BOOKTICKET_REQUEST';
export const BOOKTICKET_FAILURE = 'BOOKTICKET_FAILURE';
export const BOOKTICKET_SUCCESS = 'BOOKTICKET_SUCCESS';
export const CANCELTICKET_REQUEST = 'CANCELTICKET_REQUEST';
export const CANCELTICKET_FAILURE = 'CANCELTICKET_FAILURE';
export const CANCELTICKET_SUCCESS = 'CANCELTICKET_SUCCESS';

//Wallet
export const WALLET_REQUEST = 'WALLET_REQUEST';
export const WALLET_FAILURE = 'WALLET_FAILURE';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';


//UpdateSchedule
export const UPDATESCHEDULE_REQUEST = 'UPDATESCHEDULE_REQUEST';
export const UPDATESCHEDULE_FAILURE = 'UPDATESCHEDULE_FAILURE';
export const UPDATESCHEDULE_SUCCESS = 'UPDATESCHEDULE_SUCCESS';

//Store
export const PURCHASE_REQUEST = 'PURCHASE_REQUEST';
export const PURCHASE_FAILURE = 'PURCHASE_FAILURE';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';

//oUTPASS
export const OUTPASS_REQUEST = 'OUTPASS_REQUEST';
export const OUTPASS_FAILURE = 'OUTPASS_FAILURE';
export const OUTPASS_SUCCESS = 'OUTPASS_SUCCESS';